name: Cafe CD Staging*

on:
  pull_request:
    types:
      - closed
    branches:
      - staging

jobs:
  build_code:
    name: Build code
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup NodeJs
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
      - run: npm run build-only --if-present

      - name: Copy Assets
        run: cp -r src/assets/ dist/src/assets/

      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: dist
          retention-days: 1

  download_code:
    name: Download built code
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: write

    needs: build_code

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: Build
          path: fe-staging-3

      - name: Copy to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEV_HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          username: ${{ secrets.DEV_USER }}
          source: "fe-staging-3/*"
          target: "/var/www/sites/staging-crm/"
